/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1_franco_barra_roger_balan;

/**
 *
 * @author frank
 */
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
public class MainGUI extends javax.swing.JFrame {
    private JTabbedPane tabbedPane;
    private SistemaOperativo sistemaOperativo; // Necesitas esta referencia
    private Timer simulationTimer; 
    private static final int TIMER_DELAY = 100;

    // Referencias a los paneles para la corrección
    private SimuladorPanel simuladorPanel;
    private ConfiguracionPanel configuracionPanel;
    private GraficosPanel graficosPanel;
    private EstadisticasPanel estadisticasPanel;
    
    public MainGUI(SistemaOperativo so) {
        super("Simulador de Planificación de CPU");
        initComponents();
        
        this.sistemaOperativo = so;
        
        // --- 1. Configurar el JFrame ---
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(1300, 800);
        
        // Intentar usar un Look and Feel moderno
        try {
            UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
        } catch (Exception e) {
            // No hacer nada si falla, usa el Look and Feel predeterminado
        }

        // --- 2. Configurar el JTabbedPane y Paneles ---
        tabbedPane = new JTabbedPane();

        // Inicializar los paneles pasando la referencia del SistemaOperativo
        simuladorPanel = new SimuladorPanel(sistemaOperativo);
        configuracionPanel = new ConfiguracionPanel(sistemaOperativo);
        graficosPanel = new GraficosPanel(sistemaOperativo);
        estadisticasPanel = new EstadisticasPanel(sistemaOperativo);

        // Agregar las pestañas principales
        tabbedPane.addTab("Simulador", simuladorPanel);
        tabbedPane.addTab("Configuración", configuracionPanel);
        tabbedPane.addTab("Gráficos", graficosPanel);
        tabbedPane.addTab("Estadísticas", estadisticasPanel);

        add(tabbedPane);
        
        // --- 3. Configurar el Timer ---
        setupSimulationTimer();
        
        setVisible(true);
    }

    
       private void setupSimulationTimer() {

        ActionListener taskPerformer = new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                // 1. Ejecutar el núcleo del SO
                sistemaOperativo.avanzarCiclo(); 
                
                // 2. Actualizar la GUI
                simuladorPanel.updatePanel();
                estadisticasPanel.updatePanel();
                // configuracionPanel.updatePanel(); // Opcional, si tiene datos dinámicos
                
                // 3. Control de Finalización
                if (sistemaOperativo.isSimulationFinished()) {
                    simulationTimer.stop();
                    JOptionPane.showMessageDialog(MainGUI.this, 
                        "Simulación Terminada en Ciclo: " + sistemaOperativo.getGlobalClock(), 
                        "Fin de Simulación", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        };

        simulationTimer = new Timer(TIMER_DELAY, taskPerformer);
       }
      public void startSimulation() {
        if (!simulationTimer.isRunning()) {
            simulationTimer.start();
        }
    }
    
    public void stopSimulation() {
        if (simulationTimer.isRunning()) {
            simulationTimer.stop();
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        SimuladorPanel = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jTabbedPane6 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.PAGE_START);

        SimuladorPanel.addTab("tab1", jTabbedPane3);
        SimuladorPanel.addTab("tab2", jTabbedPane4);
        SimuladorPanel.addTab("tab3", jTabbedPane5);
        SimuladorPanel.addTab("tab4", jTabbedPane6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SimuladorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SimuladorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        SwingUtilities.invokeLater(() -> {
                   try {
                       // *** 1. Inicialización del motor de simulación ***
                       SistemaOperativo so = initializeSistemaOperativo();

                       // *** 2. Crear y mostrar la GUI ***
                       new MainGUI(so);
                   } catch (Exception e) {
                       JOptionPane.showMessageDialog(null, 
                           "Error al iniciar la aplicación: " + e.getMessage(), 
                           "Error Crítico", JOptionPane.ERROR_MESSAGE);
                       e.printStackTrace();
                   }
               });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane SimuladorPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    // End of variables declaration//GEN-END:variables
}
